### ISSUE TITLE
How do you select the classes of imagenet100 ?

### ISSUE THREAD

**Issue by cyberknight42** [wuyuebupt/LargeScaleIncrementalLearning#5]
Hi, I'm really impressed by your work and appreciate for the released codes. But can you explain how you select the classes of  ImageNet100 in details?

Thank you.

**Comment by wuyuebupt** [comment]
@JW-Xie  The imagenet100 classes should be selected by the first 100 classes in alphabet order. You may find the details at athe file https://github.com/wuyuebupt/LargeScaleIncrementalLearning/blob/master/dataImageNet100/train.txt .

**Comment by cyberknight42** [comment]
Okay. Thanks for your reply.
