### ISSUE TITLE
Question about some training params

### ISSUE THREAD

**Issue by EdenBelouadah** [wuyuebupt/LargeScaleIncrementalLearning#6]
Hello,
Thank you for the repository. 
Please, I have some questions in order to reproduce your results. 
1- Which training parameters and memory size did you use for imagenet100? In the paper, you just provide those of cifar100 and imagenet1000.
2- Can you please provide me with the image list with the class order used for cifar100 experiments?
3- Does an initial resizing of imagenet's images affects training? Did you use the original image size? (I'm not talking about the resized crop in the code, but about resizing images and storing them on the disk before training the models).
4- Do you have a complete set of results of your baseline? (Ft+distillation, before bias removal layer)

Thank you for your help

**Comment by wuyuebupt** [comment]
@EdenBelouadah Thanks for the interest in our work. Nice talking with you again:) 
1. For imagenet-100, training parameters are the same with imagenet-1000 in section 6.2 of the paper. Memory size is 2000 ( 20 samples each class for a total 100 classes, 20*100=2000). 
2. The class order of cifar is the same with icarl, which is random generated using the random seed 1993 (https://github.com/srebuffi/iCaRL/blob/master/iCaRL-TheanoLasagne/main_cifar_100_theano.py#L28).
3. We use the original image size, which are the originally downloaded ones. I don't know if some initial resizing will affect the training. The only processing we used is the vgg processing(https://github.com/wuyuebupt/LargeScaleIncrementalLearning/blob/master/vgg_preprocessing.py).
4. I don't think that I have those results. Sorry about that. But results from "before bias removal layer" can be found through the code output logs (should be the values of "accuracy_before").

**Comment by EdenBelouadah** [comment]
@wuyuebupt , nice to talk to you too and thank you for your fast reply :) 
1- Do you reduce the number of images per class when incrementing? or 20 is freezed over all states?
2-3-4- Thank you !

**Comment by wuyuebupt** [comment]
@EdenBelouadah You are welcome.
1.  Yes, the examplers for each class are reduced when incrementing, e.g. https://github.com/wuyuebupt/LargeScaleIncrementalLearning/blob/master/imagenet_main.py#L440 and https://github.com/wuyuebupt/LargeScaleIncrementalLearning/blob/master/imagenet_main.py#L489

**Comment by EdenBelouadah** [comment]
Yes, thank you, I just wanted to make sure because it was not so clear for me from your explanation. 

Thanks a lot!
